version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://perseus:perseuspass@db:5432/perseus

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  db:
    image: postgres
    environment:
      POSTGRES_USER: perseus
      POSTGRES_PASSWORD: perseuspass
      POSTGRES_DB: perseus
    ports:
      - "5432:5432"
